/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author erik.erbsloeh
 */
public class ContentPanel extends javax.swing.JPanel {

    Dimension screen;
    Image[] images;
    
    /**
     * Creates new form ContentPanel
     */
    public ContentPanel() {
	screen = Toolkit.getDefaultToolkit().getScreenSize();
        images = new Image[1];
        try {
            images[0] = ImageIO.read(new File("img//test.png"));
        } catch (IOException ex) {
            Logger.getLogger(ContentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        gamePanel.addMouseListener(gamePanel);
        
        this.setSize(screen);
        
        System.out.println(screen);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new game.ControlPanel();
        gamePanel = new game.GamePanel(8,8,images);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(controlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(screen.height, 0, screen.width-screen.height, screen.height));

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        add(gamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, screen.height, screen.height));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private game.ControlPanel controlPanel;
    private game.GamePanel gamePanel;
    // End of variables declaration//GEN-END:variables
}
