/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import javax.swing.JProgressBar;
import classes.Character;
/**
 *
 * @author erik.erbsloeh
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel(ContentPanel parent, String playername1, String playername2) {
        initComponents();
        lblTime.setText(pauseTime[0] + "");
        lblTime2.setText(pauseTime[1] + "");
        lblMessage.setText("");
        thread = new TimerThread(lblMessage, "", 0);
        ct = new CounterThread[2];
        ct[0] = new CounterThread(lblTime, null, pauseTime[0]);
        ct[1] = new CounterThread(lblTime2, null, pauseTime[1]);
        
        lblPlayer1.setText(playername1);
        lblPlayer2.setText(playername2);
        
        health = new JProgressBar[2][2];
        health[0][0] = pgbPlayer1Char1;
        health[0][1] = pgbPlayer1Char2;
        health[1][0] = pgbPlayer2Char1;
        health[1][1] = pgbPlayer2Char2;
        
        this.parent = parent;
    }

    private int turnTime = 30;
    private int[] pauseTime = {300, 300};
    private CounterThread[] ct;
    
    private JProgressBar[][] health;
    
    private ContentPanel parent;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayer1 = new javax.swing.JLabel();
        pgbPlayer1Char1 = new javax.swing.JProgressBar();
        pgbPlayer1Char2 = new javax.swing.JProgressBar();
        lblHealth = new javax.swing.JLabel();
        btnEndTurn = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        pgbPlayer2Char1 = new javax.swing.JProgressBar();
        pgbPlayer2Char2 = new javax.swing.JProgressBar();
        lblHealth1 = new javax.swing.JLabel();
        btnEndTurn1 = new javax.swing.JButton();
        btnPause1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lblPlayer1.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        lblPlayer1.setText("Player 1");

        pgbPlayer1Char1.setBackground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char1.setForeground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char1.setValue(100);

        pgbPlayer1Char2.setValue(100);

        lblHealth.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblHealth.setText("Health");

        btnEndTurn.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnEndTurn.setText("End Turn");
        btnEndTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTurnActionPerformed(evt);
            }
        });

        btnPause.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblTime.setText("5:00");

        lblTime2.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblTime2.setText("5:00");

        lblPlayer2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        lblPlayer2.setText("Player 2");

        pgbPlayer2Char1.setBackground(new java.awt.Color(255, 51, 51));
        pgbPlayer2Char1.setForeground(new java.awt.Color(255, 51, 51));
        pgbPlayer2Char1.setValue(100);

        pgbPlayer2Char2.setValue(100);

        lblHealth1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblHealth1.setText("Health");

        btnEndTurn1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnEndTurn1.setText("End Turn");
        btnEndTurn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTurn1ActionPerformed(evt);
            }
        });

        btnPause1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnPause1.setText("Pause");
        btnPause1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPause1ActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btnExit.setText("End Game");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        lblMessage.setText("MessageLabel");

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        jLabel1.setText("lblTimer");

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        jLabel2.setText("lblTimer2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTime)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHealth)
                                    .addComponent(lblPlayer1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEndTurn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pgbPlayer1Char2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pgbPlayer1Char1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEndTurn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPause1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTime2)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHealth1)
                                    .addComponent(lblPlayer2)))
                            .addComponent(pgbPlayer2Char1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pgbPlayer2Char2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 144, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer2)
                        .addGap(26, 26, 26)
                        .addComponent(lblHealth1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbPlayer2Char1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbPlayer2Char2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime2)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEndTurn1)
                            .addComponent(btnPause1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer1)
                        .addGap(26, 26, 26)
                        .addComponent(lblHealth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbPlayer1Char1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbPlayer1Char2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEndTurn)
                            .addComponent(btnPause))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        if (!ct[0].isAlive()) {
            ct[0] = new CounterThread(lblTime, null, pauseTime[0]);
            ct[0].start();
            btnPause.setText("Resume");
        }
        else {
            ct[0].interrupt();
            pauseTime[0] = ct[0].getRemainingTime();
            btnPause.setText("Pause");
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnPause1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPause1ActionPerformed
        if (!ct[1].isAlive()) {
            ct[1] = new CounterThread(lblTime2, null, pauseTime[1]);
            ct[1].start();
            btnPause1.setText("Resume");
        }
        else {
            ct[1].interrupt();
            pauseTime[1] = ct[1].getRemainingTime();
            btnPause1.setText("Pause");
        }
    }//GEN-LAST:event_btnPause1ActionPerformed

    private void btnEndTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTurnActionPerformed
        parent.getLogic().nextTurn();
    }//GEN-LAST:event_btnEndTurnActionPerformed

    private void btnEndTurn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTurn1ActionPerformed
        parent.getLogic().nextTurn();
    }//GEN-LAST:event_btnEndTurn1ActionPerformed

    private TimerThread thread;
    
    public void showMessage(String message, int duration) {
        if(thread.isAlive()) thread.interrupt();
        
        thread = new TimerThread(lblMessage, message, duration);
        thread.start();
    }
    
    public void updateHealth(Character c) {
        health[c.getPlayer()-1][c.getCharNr()].setValue(c.getHealth());
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndTurn;
    private javax.swing.JButton btnEndTurn1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPause1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealth1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JProgressBar pgbPlayer1Char1;
    private javax.swing.JProgressBar pgbPlayer1Char2;
    private javax.swing.JProgressBar pgbPlayer2Char1;
    private javax.swing.JProgressBar pgbPlayer2Char2;
    // End of variables declaration//GEN-END:variables
}
