/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author erik.erbsloeh
 */
public class ContentPanel extends javax.swing.JPanel {

    Dimension screen;
    Image[] images;
    int[][] map;
    int gpSize;
    
    private GameLogic logic;
    
    
    /**
     * Creates new form ContentPanel
     */
    public ContentPanel(String playername1, String playername2, String map) {
        
        
        
	screen = Toolkit.getDefaultToolkit().getScreenSize();
        images = new Image[7];
        try {
            images[0] = ImageIO.read(new File("img//path.png"));
            images[1] = ImageIO.read(new File("img//player1.png"));
            images[2] = ImageIO.read(new File("img//player2.png"));
            images[3] = ImageIO.read(new File("img//wall.png"));
            images[4] = ImageIO.read(new File("img//pathcross.png"));
            images[5] = ImageIO.read(new File("img//player1cross.png"));
            images[6] = ImageIO.read(new File("img//player2cross.png"));
        } catch (IOException ex) {
            Logger.getLogger(ContentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.map = FileManager.getMap(map);
        
        gpSize = ((int) screen.height/8)*8;
        
        initComponents(playername1, playername2);
        
        gamePanel.addMouseListener(gamePanel);
        
        logic = new GameLogic(this.map, gamePanel, controlPanel);
        
        this.setSize(screen);
        
        
        System.out.println(screen);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Not all generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String playername1, String playername2) {

        gamePanel = new game.GamePanel(8,8,images, map, this);
        controlPanel = new game.ControlPanel(this, playername1, playername2);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        add(gamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, gpSize, gpSize));
        add(controlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(screen.height, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public int clicked(int column, int row, int button) {
        return logic.click(column, row, button);
    }
    
    public GameLogic getLogic() {
        return logic;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private game.ControlPanel controlPanel;
    private game.GamePanel gamePanel;
    // End of variables declaration//GEN-END:variables
}
