/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import threads.PauseThread;
import threads.TimerThread;
import threads.TurnThread;
import javax.swing.JProgressBar;
import classes.Character;
import javax.swing.JButton;
import javax.swing.JLabel;
/**
 *
 * @author erik.erbsloeh
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel(ContentPanel parent, String playername1, String playername2) {
        initComponents();
        
        //<editor-fold desc="setting texts" defaultstate="collapsed">
        
        lblTime1.setText(pauseTime[0] + "");
        lblTime2.setText(pauseTime[1] + "");
        lblMessage.setText("");
        lblTurnTime1.setText(turnTime+"");
        lblTurnTime2.setText(turnTime+"");
        lblPlayer1.setText(playername1);
        lblPlayer2.setText(playername2);
        
        //</editor-fold>
        
        //<editor-fold desc="initializing threads" defaultstate="collapsed">
        
        thread = new TimerThread(lblMessage, "", 0);
        
        ct = new PauseThread(lblTime1, null, pauseTime[0], 0, this);
        
        tt = new TurnThread(lblTurnTime1, null, turnTime, GameLogic.player1, this);
        
        //</editor-fold>
        
        btnEndTurn2.setEnabled(false);
        
        //<editor-fold desc="filling arrays" defaultstate="collapsed">
        
        health = new JProgressBar[2][2];
        health[0][0] = pgbPlayer1Char1;
        health[0][1] = pgbPlayer1Char2;
        health[1][0] = pgbPlayer2Char1;
        health[1][1] = pgbPlayer2Char2;
        
        lblTime = new JLabel[2];
        lblTime[0] = lblTime1;
        lblTime[1] = lblTime2;
        
        lblTurnTime = new JLabel[2];
        lblTurnTime[0] = lblTurnTime1;
        lblTurnTime[1] = lblTurnTime2;
        
        btnPause = new JButton[2];
        btnPause[0] = btnPause1;
        btnPause[1] = btnPause2;
        
        btnEndTurn = new JButton[2];
        btnEndTurn[0] = btnEndTurn1;
        btnEndTurn[1] = btnEndTurn2;
        
        //</editor-fold>
        
        this.parent = parent;
        
        this.pauseAfter = false;
        this.gameOver = false;
        
        tt.start();
    }

    private int turnTime = 30;
    private int[] remainingTurnTime = {turnTime, turnTime};
    private int[] pauseTime = {100, 100};
    
    private PauseThread ct;
    private TurnThread tt;
    
    //<editor-fold desc="declaring arrays" defaultstate="collapsed">
    private JProgressBar[][] health;
    private JLabel[] lblTime;
    private JLabel[] lblTurnTime;
    private JButton[] btnPause;
    private JButton[] btnEndTurn;
    //</editor-fold>
    
    private ContentPanel parent;
    
    private boolean pauseAfter;
    private boolean gameOver;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayer1 = new javax.swing.JLabel();
        pgbPlayer1Char1 = new javax.swing.JProgressBar();
        pgbPlayer1Char2 = new javax.swing.JProgressBar();
        lblHealth = new javax.swing.JLabel();
        btnEndTurn1 = new javax.swing.JButton();
        btnPause1 = new javax.swing.JButton();
        lblTime1 = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        pgbPlayer2Char1 = new javax.swing.JProgressBar();
        pgbPlayer2Char2 = new javax.swing.JProgressBar();
        lblHealth1 = new javax.swing.JLabel();
        btnEndTurn2 = new javax.swing.JButton();
        btnPause2 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblTurnTime1 = new javax.swing.JLabel();
        lblTurnTime2 = new javax.swing.JLabel();

        lblPlayer1.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        lblPlayer1.setText("Player 1");

        pgbPlayer1Char1.setBackground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char1.setForeground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char1.setValue(100);

        pgbPlayer1Char2.setValue(100);

        lblHealth.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblHealth.setText("Health");

        btnEndTurn1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnEndTurn1.setText("End Turn");
        btnEndTurn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTurn1ActionPerformed(evt);
            }
        });

        btnPause1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnPause1.setText("Pause");
        btnPause1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPause1ActionPerformed(evt);
            }
        });

        lblTime1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblTime1.setText("5:00");

        lblTime2.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblTime2.setText("5:00");

        lblPlayer2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        lblPlayer2.setText("Player 2");

        pgbPlayer2Char1.setBackground(new java.awt.Color(255, 51, 51));
        pgbPlayer2Char1.setForeground(new java.awt.Color(255, 51, 51));
        pgbPlayer2Char1.setValue(100);

        pgbPlayer2Char2.setValue(100);

        lblHealth1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblHealth1.setText("Health");

        btnEndTurn2.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnEndTurn2.setText("End Turn");
        btnEndTurn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTurn2ActionPerformed(evt);
            }
        });

        btnPause2.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        btnPause2.setText("Pause");
        btnPause2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPause2ActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btnExit.setText("End Game");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        lblMessage.setText("MessageLabel");

        lblTurnTime1.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblTurnTime1.setText("lblTimer");

        lblTurnTime2.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblTurnTime2.setText("lblTimer2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 144, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblTurnTime1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTime1)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHealth)
                                    .addComponent(lblPlayer1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEndTurn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPause1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pgbPlayer1Char2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pgbPlayer1Char1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEndTurn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPause2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblTurnTime2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTime2)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHealth1)
                                    .addComponent(lblPlayer2)))
                            .addComponent(pgbPlayer2Char1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pgbPlayer2Char2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer2)
                        .addGap(26, 26, 26)
                        .addComponent(lblHealth1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbPlayer2Char1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbPlayer2Char2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime2)
                            .addComponent(lblTurnTime2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEndTurn2)
                            .addComponent(btnPause2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer1)
                        .addGap(26, 26, 26)
                        .addComponent(lblHealth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbPlayer1Char1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbPlayer1Char2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime1)
                            .addComponent(lblTurnTime1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEndTurn1)
                            .addComponent(btnPause1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPause1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPause1ActionPerformed
        if (parent.getLogic().getPlayerOnTurn() == GameLogic.player1)   pause(GameLogic.player1);
        else pauseAfter = true;
    }//GEN-LAST:event_btnPause1ActionPerformed

    private void btnPause2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPause2ActionPerformed
        if (parent.getLogic().getPlayerOnTurn() == GameLogic.player2)   pause(GameLogic.player2);
        else pauseAfter = true;
    }//GEN-LAST:event_btnPause2ActionPerformed

    private void pause(int player) {
        player -= 1;
        if (!ct.isAlive()) {
            //<editor-fold desc="stating pause" defaultstate="collapsed">
            tt.interrupt();
            remainingTurnTime[player] = tt.getRemainingTime();
            
            ct = new PauseThread(lblTime[player], null, pauseTime[player], player+1, this);
            ct.start();
            btnPause[player].setText("Resume");
            GamePanel.setClickable(false);
            //</editor-fold>
        }
        else {
            //<editor-fold desc="ending pause" defaultstate="collapsed">
            ct.interrupt();
            pauseTime[player] = ct.getRemainingTime();
            btnPause[player].setText("Pause");
            
            tt = new TurnThread(lblTurnTime[player], null, remainingTurnTime[player], player+1, this);
            tt.start();
            
            GamePanel.setClickable(true);
            //</editor-fold>
        }
    }
    
    public void endPause(int player) {
        pause(player);
    }
    
    private void btnEndTurn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTurn1ActionPerformed
        endTurn(GameLogic.player1);
    }//GEN-LAST:event_btnEndTurn1ActionPerformed

    private void btnEndTurn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTurn2ActionPerformed
        endTurn(GameLogic.player2);
    }//GEN-LAST:event_btnEndTurn2ActionPerformed

    public void endTurn(int player) {
        btnEndTurn[0].setEnabled(player == GameLogic.player2);
        btnEndTurn[1].setEnabled(player == GameLogic.player1);
        
        player -= 1;
        
        tt.interrupt();
        remainingTurnTime[player] = turnTime;
        
        parent.getLogic().nextTurn();
        
        if (!gameOver) {
        
            int playerOnTurn = parent.getLogic().getPlayerOnTurn()-1;

            tt = new TurnThread(lblTurnTime[playerOnTurn], null, turnTime, playerOnTurn, this);
            tt.start();

            if (pauseAfter) {
                pause(playerOnTurn);
                pauseAfter = false;
            }
        }
    }
    
    private TimerThread thread;
    
    public void showMessage(String message, int duration) {
        if(thread.isAlive()) thread.interrupt();
        
        thread = new TimerThread(lblMessage, message, duration);
        thread.start();
    }
    
    public void endGame(String message) {
        message = message.replace("playername1", lblPlayer1.getText());
        message = message.replace("playername2", lblPlayer2.getText());
        if(thread.isAlive()) thread.interrupt();
        lblMessage.setText(message);
        
        gameOver = true;
        
        btnPause1.setEnabled(false);
        btnPause2.setEnabled(false);
        btnEndTurn1.setEnabled(false);
        btnEndTurn2.setEnabled(false);
    }
    
    public void updateHealth(Character c) {
        health[c.getPlayer()-1][c.getCharNr()].setValue(c.getHealth());
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndTurn1;
    private javax.swing.JButton btnEndTurn2;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPause1;
    private javax.swing.JButton btnPause2;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealth1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JLabel lblTurnTime1;
    private javax.swing.JLabel lblTurnTime2;
    private javax.swing.JProgressBar pgbPlayer1Char1;
    private javax.swing.JProgressBar pgbPlayer1Char2;
    private javax.swing.JProgressBar pgbPlayer2Char1;
    private javax.swing.JProgressBar pgbPlayer2Char2;
    // End of variables declaration//GEN-END:variables
}
