/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author erik.erbsloeh
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        lblTime.setVisible(false);
        lblTime2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayer1 = new javax.swing.JLabel();
        pgbPlayer1Char1 = new javax.swing.JProgressBar();
        pgbPlayer1Char2 = new javax.swing.JProgressBar();
        lblHealth = new javax.swing.JLabel();
        btnEndTurn = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        pgbPlayer1Char3 = new javax.swing.JProgressBar();
        pgbPlayer1Char4 = new javax.swing.JProgressBar();
        lblHealth1 = new javax.swing.JLabel();
        btnEndTurn1 = new javax.swing.JButton();
        btnPause1 = new javax.swing.JButton();

        lblPlayer1.setText("Player 1");

        pgbPlayer1Char1.setBackground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char1.setForeground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char1.setValue(50);

        lblHealth.setText("Health");

        btnEndTurn.setText("End Turn");

        btnPause.setText("Pause");

        lblTime.setText("jLabel3");

        lblTime2.setText("jLabel3");

        lblPlayer2.setText("Player 2");

        pgbPlayer1Char3.setBackground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char3.setForeground(new java.awt.Color(255, 51, 51));
        pgbPlayer1Char3.setValue(50);

        lblHealth1.setText("Health");

        btnEndTurn1.setText("End Turn");

        btnPause1.setText("Pause");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbPlayer1Char2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgbPlayer1Char1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEndTurn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPause))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblTime))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHealth)
                            .addComponent(lblPlayer1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbPlayer1Char4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgbPlayer1Char3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEndTurn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPause1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblTime2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHealth1)
                            .addComponent(lblPlayer2))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer2)
                        .addGap(26, 26, 26)
                        .addComponent(lblHealth1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbPlayer1Char3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbPlayer1Char4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTime2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEndTurn1)
                            .addComponent(btnPause1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer1)
                        .addGap(26, 26, 26)
                        .addComponent(lblHealth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbPlayer1Char1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbPlayer1Char2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEndTurn)
                            .addComponent(btnPause))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndTurn;
    private javax.swing.JButton btnEndTurn1;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPause1;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealth1;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JProgressBar pgbPlayer1Char1;
    private javax.swing.JProgressBar pgbPlayer1Char2;
    private javax.swing.JProgressBar pgbPlayer1Char3;
    private javax.swing.JProgressBar pgbPlayer1Char4;
    // End of variables declaration//GEN-END:variables
}
